# Generated by Django 5.2.15 on 2026-06-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(help_text='Foto da carta enviada pelo usuário', upload_to='scans/%Y/%m/%d/', verbose_name='Imagem Original')),
                ('card_name_en', models.CharField(blank=True, default='', help_text='Nome da carta em inglês identificado pela IA', max_length=255, verbose_name='Nome (EN)')),
                ('card_name_pt', models.CharField(blank=True, default='', help_text='Nome da carta traduzido para português', max_length=255, verbose_name='Nome (PT)')),
                ('scryfall_id', models.CharField(blank=True, default='', help_text='ID único da carta na base do Scryfall', max_length=64, verbose_name='Scryfall ID')),
                ('identified', models.BooleanField(default=False, help_text='Se a carta foi identificada com sucesso', verbose_name='Identificada?')),
                ('raw_ai_response', models.TextField(blank=True, default='', help_text='Texto completo retornado pela IA de visão (debug)', verbose_name='Resposta Bruta da IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data do Scan')),
            ],
            options={
                'verbose_name': 'Scan de Carta',
                'verbose_name_plural': 'Scans de Cartas',
                'ordering': ['-created_at'],
            },
        ),
    ]
