# Generated by Django 6.0.4 on 2026-06-17 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False, help_text='Se verdadeiro, ignora limite diário de scans', verbose_name='Premium?')),
                ('scans_today', models.IntegerField(default=0, help_text='Quantidade de cartas identificadas hoje', verbose_name='Scans Hoje')),
                ('last_scan_date', models.DateField(auto_now_add=True, verbose_name='Data do Último Scan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
